variables:
  azureSubscription: "Azure for Students (e7cd92af-29f1-41f5-a42e-979c5d16e563)"
  resourcegroup: "TailwindTraderWeb"
  location: eastasia
  ImageName: website

steps:
- script: 
    echo "Listing files in Deploy directory:"
    ls "$(System.DefaultWorkingDirectory)/Deploy"
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '/Deploy/*.json'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: AzureResourceGroupDeployment@2
  displayName: Azure Deployment
  inputs:
    azureSubscription: $(azureSubscription)
    resourceGroupName: $(resourcegroup)
    location: $(location)
    csmFile: Deploy/deployment.json

- task: keesschollaart.arm-outputs.arm-outputs.ARM Outputs@6
  displayName: ARM Outputs
  inputs:
    ConnectedServiceNameARM: $(azureSubscription)
    resourceGroupName: $(resourcegroup)

- task: Docker@1
  displayName: 'Build an image'
  inputs:
    azureSubscriptionEndpoint: $(azureSubscription)
    azureContainerRegistry: $(acr).azurecr.io
    dockerFile: Source/Tailwind.Traders.Web/Dockerfile
    arguments: '-t $(acr).azurecr.io/$(ImageName):$(Build.BuildId)'
    imageName: '$(ImageName):$(Build.BuildId)'
    includeLatestTag: true

- task: Docker@1
  displayName: 'Push Image'
  inputs:
    azureSubscriptionEndpoint: $(azureSubscription)
    azureContainerRegistry: '$(acr).azurecr.io'
    command: 'Push an image'
    imageName: '$(ImageName):$(Build.BuildId)'